#!/bin/bash

declare ARKHAMDB_API_URL='https://arkhamdb.com/api/public'
declare ARKHAMDB_CACHE="${HOME}/.arkhamdb"
declare PACKS_CACHE="${ARKHAMDB_CACHE}/packs.json"
declare CARDS_CACHE="${ARKHAMDB_CACHE}/cards"
declare ALPHABETICAL_ORDER=false
declare CYCLE_ORDER=false
declare PACK_ORDER=false
declare RELEASE_ORDER=false
declare SUPER_ALPHABETICAL_ORDER=false
declare DECK_JSON

get_packs_file() {
  if [ ! -d $ARKHAMDB_CACHE ]; then
    mkdir -p $ARKHAMDB_CACHE
  fi

  if [ ! -f $PACKS_CACHE ]; then
    curl -so "$PACKS_CACHE" "${ARKHAMDB_API_URL}/packs/"
  fi

  local -a pack_ids=($(jq -r '.[] | @text "\(.code)=\(.id)"' <$PACKS_CACHE))
  local -a pack_cycles=($(jq -r '.[] | @text "cycle_\(.code)=\(.cycle_position)"' <$PACKS_CACHE))
  export "${pack_ids[@]}" "${pack_cycles[@]}"
}

get_cycle_name() {
  local -i cycle_position=$1

  case $cycle_position in
    1)
      printf 'The Night of the Zealot'
      ;;
    2)
      printf 'The Dunwich Legacy'
      ;;
    3)
      printf 'The Path to Carcosa'
      ;;
    4)
      printf 'The Forgotten Age'
      ;;
    5)
      printf 'The Circle Undone'
      ;;
    6)
      printf 'The Dream-Eaters'
      ;;
    7)
      printf 'The Innsmouth Conspiracy'
      ;;
    8)
      printf 'Edge of the Earth'
      ;;
    9)
      printf 'The Scarlet Keys'
      ;;
    10)
      printf 'The Feast of Hemlock Vale'
      ;;
    50)
      printf 'Return to...'
      ;;
    60)
      printf 'Investigator Starter Decks'
      ;;
    70)
      printf 'Side Stories'
      ;;
    80)
      printf 'Promotional'
      ;;
    90)
      printf 'Parallel'
      ;;
  esac

  printf '\n'
}

print_faction_color() {
  local faction_code="$1"
  case $faction_code in
    'survivor')
      printf '\e[91m'
      ;;
    'seeker')
      printf '\e[93m'
      ;;
    'guardian')
      printf '\e[96m'
      ;;
    'rogue')
      printf '\e[92m'
      ;;
    'mystic')
      printf '\e[95m'
      ;;
    'neutral')
      printf '\e[90m'
      ;;
  esac
}

print_card() {
  local card_json="$1"

  local card_id="$(jq -r '.code' <<<$card_json)"
  local amount=$(jq -r --arg card_id $card_id '.slots[$card_id]' <<<"${DECK_JSON}")
  local faction_code="$(jq -r '.faction_code' <<<$card_json)"
  local card_name="$(jq -r '.real_name' <<<$card_json)"
  local pack_name="$(jq -r '.pack_name' <<<$card_json)"
  local position="$(jq -r '.position' <<<$card_json)"

  printf '  %d \u00D7 ' "$amount"

  print_faction_color "$faction_code"

  printf '%s\e[0m ' "$card_name"

  printf '(%s #%d)\n' "$pack_name" "$position"
}

get_card_file() {
  local card_id="$1"

  if [ ! -d $CARDS_CACHE ]; then
    mkdir -p $CARDS_CACHE
  fi

  if [ ! -f $CARDS_CACHE/$card_id ]; then
    curl -so $CARDS_CACHE/$card_id "${ARKHAMDB_API_URL}/card/${card_id}"
  fi

  echo "$CARDS_CACHE/$card_id"
}

print_faction_heading() {
  local faction_code="$1"
  local subtype_code="$2"

  print_faction_color $faction_code

  printf ' '

  if [ "$subtype_code" = "basicweakness" ] || [ "$subtype_code" = "weakness" ]; then
    printf 'Weakness cards'
  else
    case $faction_code in
      'survivor')
        printf 'Survivor cards'
        ;;
      'seeker')
        printf 'Seeker cards'
        ;;
      'guardian')
        printf 'Guardian cards'
        ;;
      'rogue')
        printf 'Rogue cards'
        ;;
      'mystic')
        printf 'Mystic cards'
        ;;
      'neutral')
        printf 'Neutral cards'
        ;;
    esac
  fi

  printf '\e[0m\n'
}

print_factions() {
  local cards_json="$1"

  local IFS='
'
  for faction_json in $(jq -c '.[]' <<<"$cards_json"); do
    local faction_code=$(jq -r '.[0].faction_code' <<<"$faction_json")
    local subtype_code=$(jq -r '.[0].subtype_code' <<<"$faction_json")
    print_faction_heading $faction_code $subtype_code
    for card_json in $(jq -c --arg alpha $ALPHABETICAL_ORDER 'if $alpha == "true"
    then sort_by(.real_name) | .[]
    else sort_by(.pack_code as $pack | env[$pack] | tonumber) | .[] end' <<<"$faction_json"); do
      print_card "$card_json"
    done
  done
}

print_alphabetically() {
  local IFS='
'
  for card_json in $(jq -cn '[inputs] | sort_by(.real_name) | .[]' "$@"); do
    print_card "$card_json"
  done
}

print_cards() {
  local IFS='
'
  for card_json in $(jq -cn '[inputs] | sort_by(.pack_code as $pack | env[$pack] | tonumber) | .[]' "$@"); do
    print_card "$card_json"
  done
}

group_by_faction() {
  local cards_json="$1"

  jq -c 'group_by(if .faction_code == "guardian" then 1
      elif .faction_code == "seeker" then 2
      elif .faction_code == "rogue" then 3
      elif .faction_code == "mystic" then 4
      elif .faction_code == "survivor" then 5
      elif .subtype_code == "basicweakness" then 7
      elif .subtype_code == "weakness" then 7
      elif .faction_code == "neutral" then 6
      else 99 end)' <<<"$cards_json"
}

print_packs() {
  local IFS='
'
  for pack_json in $(jq -cn '[inputs] | group_by(.pack_code as $pack | env[$pack] | tonumber) | .[]' "$@"); do
    local pack_name=$(jq -r '.[0].pack_name' <<<"$pack_json")
    printf '%s\n' "$pack_name"
    local factions_json=$(group_by_faction "$pack_json")
    print_factions "$factions_json"
  done
}

print_cycles() {
  local IFS='
'
  for cycle_json in $(jq -cn '[inputs] | group_by(@text "cycle_\(.pack_code)" as $pack | env[$pack] | tonumber) | .[]' "$@"); do
    local pack_id="cycle_$(jq -r '.[0].pack_code' <<<"$cycle_json")"
    local cycle_position=$(jq -nr --arg pack_id $pack_id 'env[$pack_id]')
    local cycle_name=$(get_cycle_name $cycle_position)
    printf '%s\n' "$cycle_name"
    local factions_json=$(group_by_faction "$cycle_json")
    print_factions "$factions_json"
  done
}

print_deck() {
  local deck_name=$(jq -r '.name' <<<"$DECK_JSON")
  local investigator_name=$(jq -r '.investigator_name' <<<"$DECK_JSON")

  printf '%s (\e[90m%s\e[0m)\n' "$deck_name" "$investigator_name"

  local -a card_files
  for card_id in $(jq -r '.slots | keys | .[]' <<<"$DECK_JSON"); do
    card_files+=($(get_card_file $card_id))
  done

  if $SUPER_ALPHABETICAL_ORDER; then
    print_alphabetically "${card_files[@]}"
  elif $RELEASE_ORDER; then
    print_cards "${card_files[@]}"
  elif $CYCLE_ORDER; then
    print_cycles "${card_files[@]}"
  elif $PACK_ORDER; then
    print_packs "${card_files[@]}"
  else
    local cards_json=$(jq -cn '[inputs] | group_by(if .faction_code == "guardian" then 1
      elif .faction_code == "seeker" then 2
      elif .faction_code == "rogue" then 3
      elif .faction_code == "mystic" then 4
      elif .faction_code == "survivor" then 5
      elif .subtype_code == "basicweakness" then 7
      elif .subtype_code == "weakness" then 7
      elif .faction_code == "neutral" then 6
      else 99 end)' "${card_files[@]}")
    print_factions "$cards_json"
  fi
}

get_packs_file

while getopts 'd:l:acpr' opt; do
  case $opt in
    d)
      DECK_JSON="$(curl -s "${ARKHAMDB_API_URL}/deck/${OPTARG}")"
      ;;
    l)
      DECK_JSON="$(curl -s "${ARKHAMDB_API_URL}/decklist/${OPTARG}")"
      ;;
    a)
      if $ALPHABETICAL_ORDER; then
        SUPER_ALPHABETICAL_ORDER=true
      fi
      ALPHABETICAL_ORDER=true
      ;;
    c)
      CYCLE_ORDER=true
      ;;
    p)
      PACK_ORDER=true
      ;;
    r)
      RELEASE_ORDER=true
      ;;
  esac
done

if [ -z "$DECK_JSON" ]; then
  if [ -t 0 ]; then
    printf '\e[91mNo input!\e[0m\n' >&2
    exit 1
  fi
  read -rd '' DECK_JSON
fi

print_deck
